//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChoice
    {
        public int recNo { get; set; }
        public string catCode { get; set; }
        public string quesCode { get; set; }
        public string quesName { get; set; }
        public Nullable<int> value { get; set; }
    }
}
