//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMunCity
    {
        public string munCityCode { get; set; }
        public string munCityName { get; set; }
        public Nullable<int> district { get; set; }
        public Nullable<int> sortTag { get; set; }
    }
}
