//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSurveyByDist
    {
        public string idNo { get; set; }
        public string munCityCode { get; set; }
        public string munCityName { get; set; }
        public Nullable<int> district { get; set; }
        public string brgyCode { get; set; }
        public string brgyName { get; set; }
        public string catCode { get; set; }
        public string catName { get; set; }
        public Nullable<int> value { get; set; }
        public string quesCode { get; set; }
        public string quesName { get; set; }
        public Nullable<int> sampleSize { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> wave { get; set; }
    }
}
